export const ACTION_TYPE = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  GET_ALL_TASKS: "GET_ALL_TASKS",
  SET_LOADING: "SET_LOADING",
  ADD_TODO: "ADD_TODO",
  COMPLETE_TASK: "COMPLETE_TASK",
  DELETE_TASK: "DELETE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
};
